# Generated by Django 5.1.2 on 2024-11-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_word', '0002_words_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='date',
            field=models.CharField(max_length=300),
        ),
    ]
