# Generated by Django 5.1.2 on 2024-11-01 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_word', '0003_alter_words_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='date',
        ),
        migrations.AddField(
            model_name='words',
            name='date_dj',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='words',
            name='date_str',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 1, 19, 25, 13, 941965)),
        ),
    ]
