# Generated by Django 5.1.2 on 2024-11-01 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_word', '0004_remove_words_date_words_date_dj_words_date_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='date_str',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
